### ISSUE TITLE
Ne marche pas mais j'ai la solution

### ISSUE THREAD

**Issue by Sn0wAlice** [souProjet/SelfEmployed#1]
En fait c'est tout con..
Le module Cookie n'existe plus sur les nouvelle vertion de deno http. DONC il est obligatoire de passer par une URL qui précise la vertion

Du coup il faut aller voir: https://deno.land/std@0.104.0/http
Avec par exemple les utilisation suivante: 
`import { getCookies } from "https://deno.land/std@0.104.0/http/cookie.ts";` et non `import { getCookies } from "https://deno.land/std/http/cookie.ts";`

**Comment by Sn0wAlice** [comment]
donc en soit app faut changer le site.ts

**Comment by souProjet** [comment]
j'ai le même problème pour le module mysql mais je trouve pas le lien qui correspond à la bonne version

**Comment by souProjet** [comment]
Error: Currently cannot support auth method mismatch!
    at PoolConnection._connect (https://deno.land/x/mysql@v2.10.2/src/connection.ts:104:17)
    at async PoolConnection.connect (https://deno.land/x/mysql@v2.10.2/src/connection.ts:148:5)
    at async Client.createConnection (https://deno.land/x/mysql@v2.10.2/src/client.ts:47:5)
    at async DeferredStack.creator (https://deno.land/x/mysql@v2.10.2/src/pool.ts:61:20)
    at async DeferredStack.pop (https://deno.land/x/mysql@v2.10.2/src/deferred.ts:35:16)
    at async ConnectionPool.pop (https://deno.land/x/mysql@v2.10.2/src/pool.ts:93:14)
    at async Client.useConnection (https://deno.land/x/mysql@v2.10.2/src/client.ts:105:24)
    at async Client.query (https://deno.land/x/mysql@v2.10.2/src/client.ts:85:12)
    at async sql_query.query_select (file:///home/***/SelfEmployed/class/query.ts:25:18)
    at async home_func.modif (file:///home/***/SelfEmployed/class/modif/home.ts:7:20)

**Comment by souProjet** [comment]
Résolu après avoir rajouter : `default_authentication_plugin=mysql_native_password` dans /etc/mysql/mysql.conf.d/mysqld.cnf
